### ISSUE TITLE
Labels of increase and decrease buttons are empty

### ISSUE THREAD

**Issue by picobulgarelli** [cemolcay/TempoStepper#2]
Label for increase and decrease buttons are empty. I can't change them and I can't fix the issue because TempoStepper is a framework library.

Project updated for Swift 5.1, simulator on iOS 13.3

![Simulator Screen Shot](https://user-images.githubusercontent.com/48985589/75855675-10e37680-5df3-11ea-9fa9-7a3e8d0906d1.png)

**Comment by cemolcay** [comment]
Hi! I updated the example project. 
And also released a new version for Swift 5.0+ support.

You can set your images programmatically or through the storyboard:
<img width="1329" alt="Screen Shot 2020-05-28 at 15 51 11" src="https://user-images.githubusercontent.com/2419578/83143854-3edb0d00-a0fb-11ea-8966-7de76df81ed2.png">
